### ISSUE TITLE
ip4.exe gets flagged by antivirus

### ISSUE THREAD

**Issue by jpruiz114** [Treer/ip4#1]
![image](https://user-images.githubusercontent.com/4614970/78518973-e38e3d80-778f-11ea-85c1-c3d77040208a.png)

**Comment by jpruiz114** [comment]
![image](https://user-images.githubusercontent.com/4614970/78519015-f99bfe00-778f-11ea-8715-d862b8682161.png)

**Comment by jpruiz114** [comment]
![image](https://user-images.githubusercontent.com/4614970/78519022-04ef2980-7790-11ea-8d4a-e0d0763c4693.png)

**Comment by jpruiz114** [comment]
@Treer tagging you here to get some visibility on the issue, thanks.

**Comment by Treer** [comment]
Thanks for tagging me in. There's no adware in ip4.exe so I assume a false positive, but none of those screenshots mention ip4.exe

Could you be more specific about what's happening and when it happens? It is what you see when downloading https://github.com/Treer/ip4/releases/download/v1.0.4/ip4.exe ?

Avast have a webpage when I can claim it'ss a false positive, but I'll need to know where the file came from to ensure it's the right version.

Edit: I've gone ahead and submitted v1.0,4 anyway, supposedly they will email me back.

**Comment by Treer** [comment]
From: support\<at\>help2.avast.com
> Hello,
>
> Thank you for reporting this false positive.
>
> Our virus specialists have now cleared its reputation in our database.
>
> With URLs this change should be instant, but it might take up to 24 hours with files.
>
> For future reference you might also find the following article to be useful: [Avast Clean Guidelines](https://support.avast.com/en-us/article/228/).
>
>Best regards,
>
>Avast Customer Care

@jpruiz114  If after the 24 hours you confirm that Avast no longer flags it, feel free to delete the comment on stackoverflow - it'll probably be scaring some people off ;)
